Blog app - Views
mohisa302/Blog-app pull request #6
Opened 2023-05-13 19:23 UTC by mohisa302

###  Views
In this PR I:

- Implemented the design from the sneak peek wireframes
- Each URL view image in the following:
  - `http://127.0.0.1:3000/users`
  
    ![image](https://github.com/mohisa302/Blog-app/assets/96848068/d9ea40b6-8f45-4403-871e-938bbc2afd19)
 
  -` http://127.0.0.1:3000/users/2`
    ![image](https://github.com/mohisa302/Blog-app/assets/96848068/dff37dcd-abdd-4b36-ac76-a5471bc2717d)

  - `http://127.0.0.1:3000/users/2/posts`
  
   ![image](https://github.com/mohisa302/Blog-app/assets/96848068/dff37dcd-abdd-4b36-ac76-a5471bc2717d)
   ![image](https://github.com/mohisa302/Blog-app/assets/96848068/23f67e4a-1db3-4db8-b214-844c020a20b7)

  - `http://127.0.0.1:3000/users/2/posts/4`
    ![image](https://github.com/mohisa302/Blog-app/assets/96848068/9ff3e12a-9766-442d-9ac0-15c416f87993)

2023-05-13 20:16 UTC, MeqdamAlqudah requested changes
Hi @mohisa302  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://github.com/mohisa302/Blog-app/assets/74744787/1ed7eeb5-abb8-4812-9c0f-b6d2db1de804)


## Highlights
:+1: adding users
:+1: listing posts and comments 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- add links to the post index page the post should send you to the post show page and so on 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 20:16 UTC, MeqdamAlqudah commented on app/views/users/index.html.erb
> +    <!-- display user's posts, comments, likes, etc. -->
- [ ] Please Clicking on each user should take the user to their show page , currently there is no link in the user index page for each user please fix this , so the users can navigate easly through your app.

2023-05-13 20:16 UTC, MeqdamAlqudah commented on app/views/users/show.html.erb
> +<button class="border p-6 font-bold" style="width:20%; margin-left:40%;">See all posts</button>
- [ ] Please **See all Post** links should opens user's post index , currently this button doesn't do anything,

2023-05-13 20:16 UTC, MeqdamAlqudah commented on app/views/posts/show.html.erb
> +      <% end %>
- [ ] Please currently the user can see the comment id and the comment writer name , but he can't see the text of the comment please add it so the user can see the comment info .

2023-05-13 20:16 UTC, MeqdamAlqudah commented on app/views/users/show.html.erb
> +        <p class="mt-4"><%= post.text %></p>
- [ ] Please currently the comments box doesn't match the design , please fix it ,the comments should be in a one box I see that each is in different box in your code
 
| your Design | original|
| ------------------ | ---------- |
| ![image](https://github.com/mohisa302/Blog-app/assets/74744787/3433554b-573e-4e5d-bbd0-cd3607b854b3) | ![image](https://github.com/mohisa302/Blog-app/assets/74744787/6bd26dda-d759-49f5-b569-d05386c7d911) |

2023-05-20 15:34 UTC, m05e5 requested changes
Hi @mohisa302 , 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-20 15:34 UTC, m05e5 commented on app/views/posts/show.html.erb
> +      <div>
- [ ] Great job but as part of the requirements, the `show` `post` page is supposed to display all the comments, not just the first 5. Please kindly fix it

2023-05-20 15:48 UTC, m05e5 approved these changes
**Hi @mohisa302 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights


✔️ Clean Codebase
✔️ No linters error

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-05-20 15:48 UTC, m05e5 approved these changes
**Hi @mohisa302 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights


✔️ Clean Codebase
✔️ No linters error

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-05-20 15:48 UTC, m05e5 approved these changes
**Hi @mohisa302 
You did great. Your project is complete!  There is nothing else to say other than... it's time to merge:shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights


✔️ Clean Codebase
✔️ No linters error

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-05-20 15:49 UTC, merged